root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/chamaelas-api ."
  entrypoint = "./tmp/chamaelas-api"
  include_ext = ["go", "sql", "env", "html"]
  exclude_dir = ["tmp", "data", "frontend"]
  delay = 300
  stop_on_error = true

[log]
  time = true

[color]
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"

[misc]
  clean_on_exit = true
